ML DataLoaders
CrayLabs/SmartSim pull request #115
Opened 2021-12-02 23:35 UTC by al-rigazzi

**This is still a draft (some docs and tests missing).**

2021-12-09 18:53 UTC, Spartee reviewed
Will you run `make style` on this before I place in review comments?

2021-12-15 00:13 UTC, Spartee commented
Went to review and looks like there are still a couple conflicts @al-rigazzi

2022-01-17 21:07 UTC, Spartee requested changes
Couple things

1. make sure to throw the deprecation wanring for ``smartsim.tf`` and lets let the user import that for a release. basically an empty module with the dep and an import works here. use the ``warnings`` library and throw ``DeprecationWarning``
2. Some re-naming for brevity
3. Lets add tests for all of these in the ``tests/backends`` folder.
4. Use the logger.
5. Lotta copy paste, lets keep the comments to what users need to see and direct them to the places they need to go for more information if necessary. These should be easy to grok in a VSCode like editor
6. instead of ``smartsim.ml.tf.data`` lets have those imports resolve to ``smartsim.ml.tf`` for brevity.
7. Workers comment may be in a differnt ticket but lets expose that if the functionality works and be sure to document the decision there.
8. tests tests tests tests

2022-01-21 23:21 UTC, MattToast reviewed
Supper cool looking stuff!! Here's some quick notes for consideration:

- I'm gonna second shortening up the docstrings to essential information. As someone coming from the outside, it took me while to try and figure out how the sub-classes differed while searching through the boilerplate.
- Found a couple of minor errors in the docs.
- Marked some places in where I thought the code-style seemed a bit off. Address as you see fit.

2022-01-31 15:28 UTC, al-rigazzi commented on smartsim/ml/data.py
> +        smartredis_cluster=True,
Done

2022-01-31 15:29 UTC, al-rigazzi commented on smartsim/ml/data.py
> +    :type smartredis_cluster: bool
Done

2022-01-31 15:33 UTC, al-rigazzi commented on smartsim/ml/data.py
> +    :param replica_rank: When BatchDownloader is used in a distributed setting, indicates
Yeah, this was confusing. The sub-indices are those of the uploader, I renamed them as `uploader_ranks`, which is just an `int`.

2022-01-31 15:33 UTC, al-rigazzi commented on smartsim/ml/torch/data.py
> +    def worker_init_fn(worker_id):
Both are handled by the super-class `torch.DataLoader` and corresponding settings.

2022-01-31 15:34 UTC, al-rigazzi commented on tutorials/04_ml_training/tf/data_uploader.py
> +from mpi4py import MPI
I put it in the Jupyter notebook, should be enough, but I'm open to suggestions.

2022-01-31 15:36 UTC, al-rigazzi commented on smartsim/ml/data.py
> +from smartredis.error import RedisReplyError
Removed

2022-01-31 17:36 UTC, al-rigazzi commented on tutorials/04_ml_training/torch/training_service_hvd.py
> +import numpy as np
Fixed

2022-01-31 17:36 UTC, al-rigazzi commented on tutorials/04_ml_training/torch/training_service.py
> +import numpy as np
Fixed

2022-01-31 17:36 UTC, al-rigazzi commented on tutorials/04_ml_training/tf/training_service_hvd.py
> +import numpy as np
Fixed

2022-01-31 17:37 UTC, al-rigazzi commented on smartsim/ml/torch/data.py
> +        print(f"{worker_id}: {sources}")
Well, this was too verbose anyhow. I removed it.

2022-01-31 17:43 UTC, al-rigazzi commented on doc/tutorials/machine_learning.rst
> +    exp = ("online-training", launcher="local")
Good catch

2022-01-31 17:43 UTC, al-rigazzi commented on doc/tutorials/machine_learning.rst
> +    uploader_model.attach_generator_files(to_copy=script)
Fixed

2022-01-31 17:44 UTC, al-rigazzi commented on doc/tutorials/machine_learning.rst
> +    settings = RunSettings("python", exe_args=training_script)
Done

2022-01-31 17:44 UTC, al-rigazzi commented on smartsim/ml/data.py
> +                    "Not enough samples in generator for one batch. Please run init_samples() or initialize generator with init_samples=True"
Yep, split over two lines, thanks

2022-01-31 17:46 UTC, al-rigazzi commented on smartsim/ml/data.py
> +        else:
Removed

2022-01-31 17:46 UTC, al-rigazzi commented on smartsim/ml/tf/data.py
> +from os import environ
Fixed

2022-01-31 17:47 UTC, al-rigazzi commented on smartsim/ml/torch/data.py
> +        worker_id = worker_info.id
I defer to the Torch docs I took this from. My best guess is that it is not.

2022-01-31 18:50 UTC, al-rigazzi commented on doc/tutorials/machine_learning.rst
> +    settings = RunSettings("python", exe_args=producer_script)
Fixed

2022-01-31 18:53 UTC, al-rigazzi commented on doc/tutorials/machine_learning.rst
> +    uploader_model = exp.create_model("producer", settings)
I had no clue we could do that.

2022-01-31 18:54 UTC, al-rigazzi commented on doc/tutorials/machine_learning.rst
> +    exp.start(uploader_model, block=False, summary=False)
Done

2022-01-31 19:05 UTC, al-rigazzi commented on smartsim/ml/tf/data.py
> +        return StaticDataGenerator.__data_generation(self, indices)
Very good catch, it was legacy code

2022-01-31 19:06 UTC, al-rigazzi commented on smartsim/ml/data.py
> +      `uploader_name`. BatchDownloader will get all needed information
Yep, now I fixed all names.

2022-01-31 19:06 UTC, al-rigazzi commented on smartsim/ml/data.py
> +    def log(self, message):
OK, added logger now!

2022-01-31 19:06 UTC, al-rigazzi commented on doc/tutorials/machine_learning.rst
> +    exp.start(uploader_model, block=False, summary=False)
Done

2022-02-03 20:52 UTC, Spartee approved these changes
LGTM! Great work! Excited to see the propagate into the community.

2022-02-03 22:01 UTC, merged