Automatic launcher detection
CrayLabs/SmartSim pull request #120
Opened 2021-12-17 09:27 UTC by al-rigazzi

This PR adds the automatic launcher detection to `Experiment` and to `create_run_settings` and `create_batch_settings`.

Two detect the launcher, we check that all commands specified in the corresponding `<launcher>Commands.py` file are available.
To distinguish between Cobalt and PBS, we call `qsub --version` and parse its output.

2021-12-21 21:06 UTC, Spartee requested changes
Few comments. Most important being the module placement. Lets chat about that whenever you have a chance.

2021-12-21 21:06 UTC, Spartee commented on smartsim/experiment.py
> +                         "cobalt", "lsf", or "local", if set to "auto",
Period instead of comma

2021-12-21 21:06 UTC, Spartee commented on smartsim/experiment.py
> +from .utils.helpers import colorize, detect_launcher, init_default
Is a user ever going to want to use this function? If so, we may considering creating a new module thats more user facing as the helpers are going to be moved to the ``_core`` directory.

I think it's possible a user may want to inspect the value returned by ``detect_launcher`` for specific use cases. I could go either way on this one. If you don't think so, just leave it.

If you do think we should have a module, names?

``expUtils``?
``wlmUtils``?
``wlm``? 

I could see the last one being good if we end up moving the slurm (allocation) api to the ``wlm`` module.

2022-01-11 22:27 UTC, Spartee approved these changes
Please see one comment and make sure that test case will pass. otherwise LGTM.

2022-01-12 15:25 UTC, al-rigazzi commented on tests/test_experiment.py
> +    exp = Experiment("test-launcher-detection", launcher="auto")
I moved this test to `on_wlm`. The only case we cannot test, this way, is if the detected launcher is `local`. I think it is quite a corner case (and the default value anyhow) and testing for it is not too relevant, but I'm open to suggestions.

2022-01-12 20:28 UTC, merged