Fix re-run smart build bug
CrayLabs/SmartSim pull request #165
Opened 2022-03-02 19:54 UTC by EricGustin

This PR fixes #162. If the user attempts to re-run `smart build` before running `smart clean`, then a message will be logged with level ERROR, notifying the user that they must first run `smart clean`. In addition, after `smart build` is ran, a message is logged with level INFO, notifying which backends are built.

2022-03-04 02:41 UTC, Spartee requested changes
Overall this is great. There is one problem which I did not forsee writing up the ticket. The function ``installed_redisai_backends`` accounts for the fact that the backends may be installed site-wide at the ``RAI_PATH`` which is our plan for smartsim module files (see https://github.com/craylabs/poseidon/issues/176).

This function will stop users from trying to build when they already have the backends built somewhere, but the error message isn't super helpful. They might even try to run ``smart clean`` and then find out they are still greeted with the same message if they still have the modulefile loaded.

Leaning on @al-rigazzi and @ashao to make suggestions here. Requesting changes as I think we need to address this first as site-wide installs are part of the plan.

2022-03-09 21:08 UTC, al-rigazzi commented
Yeah, I think the user should be notified if `smart clean` will not be effective. One possibility would be to explicitly tell the user where the backends are installed, and what actions could be useful (i.e. build your own SmartSim or change `RAI_PATH`, maybe?)

2022-03-10 21:03 UTC, Spartee commented
@al-rigazzi I agree. I think the best plan is to allow them to build and use the backends they want to build seperately if need be. But the default should be to use the set `RAI_PATH` and `REDIS_PATH` etc, and prompt the user that the backends are already built at a specific location. 

It would be best if there was some way for the user to also install the recommended ML backends provided the RAI version that was installed. this would enabled site-install users to run

```bash
# create python env
module load smartsim-0.4.0-rai-1.2.3
smart build --install-ml
```

this would essentially skip the build process if the backends were module loaded into the environment and then install the correct python dependencies into the user environment.

what do you think @al-rigazzi ?

2022-03-10 21:04 UTC, al-rigazzi commented
Yes, I agree with @Spartee, that would be cleaner (and automatically documented through `smart --help`).

2022-03-18 22:47 UTC, EricGustin commented
@Spartee @al-rigazzi changes have been made to address your comments.

2022-03-19 00:05 UTC, Spartee approved these changes
One small change, otherwise good to merge! Feel free to merge after that comment is edited.

2022-03-19 00:05 UTC, Spartee commented on smartsim/_core/_cli/build.py
> +                    f"Backends are already built and loaded at '{CONFIG.redisai}'. There is no need to build."
mention that they are specified in the environment at ``RAI_PATH`` so the user is aware thats where they are specified.

2022-03-19 21:42 UTC, merged