Mpiexec Patch
CrayLabs/SmartSim pull request #192
Opened 2022-04-26 15:56 UTC by MattToast

Updates the  `MpiexecSettings` (and all other OpenMPI settings classes) to use `subprocess.run` as opposed to `subprocess.check_output` when checking version statements so that it can handle a non-zero status return code.

2022-04-26 18:15 UTC, Spartee requested changes

2022-04-27 18:30 UTC, MattToast commented on smartsim/settings/mpirunSettings.py
> +        c_proc = sp.run(
Made the implicit explicit in [f2362cd](https://github.com/CrayLabs/SmartSim/pull/192/commits/f2362cdd14c9f541ab98ade7d025dbf82cfa0c34)

2022-04-27 18:31 UTC, MattToast commented on smartsim/settings/mpirunSettings.py
> +        c_proc = sp.run(
Made the implicit explicit some more in [f2362cd](https://github.com/CrayLabs/SmartSim/pull/192/commits/f2362cdd14c9f541ab98ade7d025dbf82cfa0c34)

2022-05-10 15:33 UTC, al-rigazzi commented
@Spartee I think the changes you requested have been implemented. The codecov dip seems to be due to a new way of computing coverage (see #194).

2022-05-10 15:34 UTC, al-rigazzi approved these changes
LGTM

2022-05-17 23:20 UTC, merged