exclude csv-valued env values from --export, enable csv-valued in mpmd
CrayLabs/SmartSim pull request #268
Opened 2023-03-08 23:23 UTC by ankona

This PR fixes two defects related to passing environment variables to slurm jobs.

1. CSV-valued environment variables are not passed to MPMD executions
2. CSV-valued environment variables are passed twice

For (1), add populating source env with `env k1=v1,v2 {srun} --export k1`

For (2), perform key-only export of csv-valued vars:
- old: env k1=v1,v2 srun --export k1=v1,v2
- new: env k1=v1,v2 srun --export k1

2023-03-10 13:52 UTC, al-rigazzi approved these changes
Good catch! LGTM

2023-03-10 23:39 UTC, ashao requested changes
Can you confirm that passing just the name of a variable (e.g. just `foo` with no value) leads to an export argument that looks like
```
--export foo,k=1
```

2023-03-13 16:20 UTC, ankona commented
> Can you confirm that passing just the name of a variable (e.g. just `foo` with no value) leads to an export argument that looks like
> 
> ```
> --export foo,k=1
> ```

I thought this could be a fairly simple addition. Unfortunately, it seems like it's not a currently supported feature and would require me to make more changes than expected. 

For example, check out this [type checking](https://github.com/CrayLabs/SmartSim/blob/develop/smartsim/settings/base.py#L383-L386). This bit of code would make it impossible to add variables without values without changing & potentially weakening this feature.

Another example is the [default formatting behavior](https://github.com/CrayLabs/SmartSim/blob/develop/smartsim/settings/base.py#L520-L526). It assumes a key-value pair and would need to be updated.

I added a new [task ](https://github.com/CrayLabs/SmartSim-EE/issues/301) to review this. I'd like to solve this, but not in the existing task

2023-03-13 21:43 UTC, al-rigazzi requested changes
As discussed, let's update comments and add the `ALL` keyword to `env_var_str` (I think this could happen in the format function, but I leave it up to you). Sorry for the misunderstanding!

2023-03-14 18:22 UTC, al-rigazzi approved these changes
LGTM, thanks for the last-minute updates!

2023-03-15 16:00 UTC, ashao approved these changes
Looks great! Thanks for making those changes and having such complete test coverage.

2023-03-15 16:15 UTC, merged