Adding affinity scripts to PALS mpiexec settings
CrayLabs/SmartSim pull request #282
Opened 2023-05-03 15:14 UTC by rickybalin

Added an option to specify an affinity script for the PALS mpiexec settings and add it to the run command after the run arguments, with no "--" prefix. This feature is needed when running multiple applications on the same nodes with the co-located deployment and the applications have to share the GPU on each node.

2023-08-29 16:20 UTC, rickybalin commented
I was wondering if there were any updates on this pull request. The ability to specify a GPU affinity script to the run settings is very useful when sharing the GPU on each node between multiple applications.

2023-10-10 18:10 UTC, al-rigazzi requested changes
Thanks for this contribution, @rickybalin! A couple of minor things to address before we can merge:
1. Can you resolve merge conflicts and address my comment?
2. Then you should be able to run `make check-mypy` and `make check-lint` to make sure all tests will pass
3. May I ask you to add a test to check that the affinity parameter(s) are correctly added to this kind of Run Settings?

Thanks (and sorry for catching up so late)!

2023-10-10 18:10 UTC, al-rigazzi commented on smartsim/settings/palsSettings.py
> +    def set_gpu_affinity_script(self, affinity, *args):
So, here the idea would be to let the user add more than one file?
Also, I think you will need to add typehints, so possibly the declaration will be:
```python
def set_gpu_affinity_script(self, affinity: str, *args: str) -> None:

2023-10-17 22:06 UTC, al-rigazzi reviewed
Everything looks good! If you could just add a test for the new feature, I think this is ready to go!

2023-10-18 16:01 UTC, rickybalin commented
> Everything looks good! If you could just add a test for the new feature, I think this is ready to go!

Done.

2023-10-18 17:28 UTC, merged