Mitigate suppressed protected-access errors from pylint
CrayLabs/SmartSim pull request #341
Opened 2023-08-15 21:26 UTC by ankona

2023-08-16 15:08 UTC, mellis13 requested changes
Thanks for fixing these lint suppressions.  It seems like ``DBModel`` and ``DBScript`` are more visible to the user now that they are properties.  Do you think it's worth making a ticket to look through these objects and make sure they have basic user-functionality for inspection (e.g. ``__str__``).

2023-08-16 18:31 UTC, ankona commented on smartsim/entity/model.py
> +        return (model for model in self._db_scripts)
derp. copypasta fail. 100

2023-08-16 18:36 UTC, ankona commented on smartsim/entity/entityList.py
> +        return (model for model in self._db_scripts)
100. Done!

2023-08-16 18:37 UTC, ankona commented on smartsim/entity/model.py
> +        """Return an immutable collection of db scripts attached to the Model"""
Shortened to avoid the type self-referencing in the comment.

2023-08-21 10:49 UTC, ankona commented
Ticket 511 created @mellis13

2023-08-21 16:02 UTC, mellis13 approved these changes
LGTM -- thanks!

2023-08-22 14:43 UTC, merged