Update documentation surrounding contributions
CrayLabs/SmartSim pull request #344
Opened 2023-08-22 23:14 UTC by ashao

Pulls together and creates some new guidelines on how to contribute to SmartSim.

2023-08-23 17:27 UTC, juliaputko approved these changes
Looks good to me

2023-08-23 18:15 UTC, al-rigazzi requested changes
One typo to fix, then LGTM! Great stuff!

2023-08-23 18:15 UTC, al-rigazzi commented on doc/contributing.rst
> +1. **Please ask only in one place.** Please restrict yourself to posting your
Should be `2.`

2023-08-24 00:48 UTC, billschereriii commented
Corrected a typo that I saw. Otherwise looks great

2023-08-24 14:50 UTC, al-rigazzi approved these changes
LGTM!

2023-08-24 15:42 UTC, ankona approved these changes

2023-09-01 20:29 UTC, merged