DB proper shutdown
CrayLabs/SmartSim pull request #355
Opened 2023-09-05 14:16 UTC by al-rigazzi

This PR changes the way `Orchestrator`s are stopped.

Currently, the `Orchestrator` process or job is simply killed: this proved not to be a good technique with some WLMs, where the launcher and the launched process are different. In such cases, it is impossible to stop a running process and orchestrators stay up until the allocation is relinquished.

With this PR, we added the execution of an explicit `shutdown` command for each DB shard, which properly terminates the Orchestrator in all cases.

2023-09-06 18:28 UTC, MattToast requested changes
Couple of small knit picks, but otherwise LGTM!!

2023-09-06 20:10 UTC, al-rigazzi commented on tests/backends/test_dbmodel.py
> +from smartsim.entity import ensemble
Note to self: never click the first result in the "Quick fix" context menu.

2023-09-08 18:57 UTC, al-rigazzi commented on smartsim/_core/utils/redis.py
> +            cmd += ["shutdown"]
Pedantic, but right.

2023-09-08 18:58 UTC, al-rigazzi commented on smartsim/_core/utils/redis.py
> +        for port in ports:
Nice!

2023-09-08 18:59 UTC, al-rigazzi commented on smartsim/_core/utils/redis.py
> +            logger.debug(out)
You mean the `logger.debug(out)` line?

2023-09-08 19:02 UTC, al-rigazzi commented on smartsim/database/orchestrator.py
> +              and hasattr(self.dbnodes[0].run_settings, "mpmd")):
Correct, indeed

2023-09-08 19:02 UTC, al-rigazzi commented on smartsim/settings/palsSettings.py
> +        self.run_args["hosts"] = ",".join(host_list)
Yeah, technically `host` works too, but I prefer to comply to their docs.

2023-09-08 19:03 UTC, al-rigazzi commented on smartsim/settings/palsSettings.py
> +        """Set the hostlist for the PALS ``mpirun`` command
Done

2023-09-11 12:29 UTC, al-rigazzi commented on smartsim/_core/utils/redis.py
> +            logger.debug(out)
Done

2023-09-11 16:04 UTC, MattToast approved these changes
LGTM!! Thanks for adding this; this is definitely a much more clean way of tearing down DBs!!

2023-09-18 20:55 UTC, merged