Add support for MINBATCHTIMEOUT
CrayLabs/SmartSim pull request #387
Opened 2023-10-05 21:42 UTC by billschereriii

Paralleling the implementation of support for min_batch_size

2023-10-05 21:58 UTC, al-rigazzi requested changes
Everything looks good except for a tiny typo in the changelog. Otherwise LGTM!

2023-10-05 21:58 UTC, al-rigazzi commented on doc/changelog.rst
> +  .. _PR384: https://github.com/CrayLabs/SmartSim/pull/387
`_PR384` -> `_PR387`

2023-10-06 19:03 UTC, ashao approved these changes
Looks good. Thanks!

2023-10-06 19:09 UTC, al-rigazzi approved these changes
LGTM! Thanks for addressing this so quickly!

2023-10-06 19:21 UTC, merged