Add cooldown period to avoid immediate termination of telemetry monitor
CrayLabs/SmartSim pull request #416
Opened 2023-11-13 17:16 UTC by ankona

2023-11-14 20:55 UTC, ankona commented on tests/test_telemetry_monitor.py
> +        assert popen.returncode is not None
should add an `assert elapsed >= cooldown` to ensure it was really honored

2023-11-15 17:27 UTC, AlyssaCote reviewed
This looks good to me! 👍

2023-11-20 19:52 UTC, ankona commented on tests/test_telemetry_monitor.py
> +        assert popen.returncode is not None
added

2023-11-21 22:08 UTC, al-rigazzi requested changes
A couple of minor typos, otherwise looks good!

2023-11-21 22:08 UTC, al-rigazzi commented on smartsim/_core/entrypoints/telemetrymonitor.py
> +        logger.debug(f"telemetry monitor is monitoring {len(jobs)} dbs")
`jobs` -> `db_jobs` ?

2023-11-21 22:08 UTC, al-rigazzi commented on smartsim/_core/entrypoints/telemetrymonitor.py
> +        help="Default lifetime of telemetry monitor (in seconds)) before auto-shutdown",
Two )) for only one (

2023-11-22 16:50 UTC, ankona commented on smartsim/_core/entrypoints/telemetrymonitor.py
> +        logger.debug(f"telemetry monitor is monitoring {len(jobs)} dbs")
great eye. fixed

2023-11-22 16:51 UTC, ankona commented on smartsim/_core/entrypoints/telemetrymonitor.py
> +        help="Default lifetime of telemetry monitor (in seconds)) before auto-shutdown",
Fixed!

2023-11-22 19:36 UTC, al-rigazzi approved these changes
LGTM!

2023-11-27 16:24 UTC, merged