Removed Slurm specific methods from LaunchArguments
CrayLabs/SmartSim pull request #662
Opened 2024-08-08 23:34 UTC by juliaputko

2024-08-12 21:50 UTC, MattToast requested changes
Looks great! Just a couple of sanity checks!!

2024-08-12 21:50 UTC, MattToast commented on smartsim/_core/arguments/shell.py
> +    from smartsim.settings.arguments import LaunchArguments
Latter import shadows the former. Looks like these are pointing to the same type though, so you should be free to just drop the second:
```suggestion
from smartsim.settings.arguments.launchArguments import LaunchArguments
```

2024-08-12 21:50 UTC, MattToast commented on smartsim/_core/arguments/shell.py
> +    def format_launch_args(self) -> t.Union[t.List[str], None]: ...
Very minor nit: while we're here can we upgrade to the new style type hints?
```suggestion
    @abstractmethod
    def format_env_vars(
        self, env_vars: dict[str, str | None]
    ) -> list[str] | None: ...

    @abstractmethod
    def format_launch_args(self) -> list[str] | None: ...
```

2024-08-12 21:50 UTC, MattToast commented on smartsim/_core/arguments/shell.py
> +        self, env_vars: t.Dict[str, t.Optional[str]]
pedantic interface question: does `env_vars` here need to be a `dict`? If we are not planning to write into it, could it instead be a `t.Mapping`? The only reason I ask is becuase currently this fails type check:
```py
import os
my_args: ShellLaunchArguments = ...
my_args.format_env_vars(os.environ)
```

2024-08-12 21:50 UTC, MattToast commented on smartsim/_core/arguments/shell.py
> +    def format_launch_args(self) -> t.Union[t.List[str], None]: ...
Similar pedantic interface question: does this return type need to be nullable? If so, what is the difference between returning `None` and returning `[]`?

2024-08-20 19:01 UTC, juliaputko commented on smartsim/_core/dispatch.py
>              (
talked about offline. New ticket created

2024-08-20 19:01 UTC, juliaputko commented on smartsim/settings/launchSettings.py
> +    #     return self._arguments.format_launch_args()
removed

2024-08-20 20:36 UTC, MattToast approved these changes
A couple of slightly tighter type hints if you want, and some small style failures in the CI, but otherwise looks about ready on my end!

LGTM!!

2024-08-20 21:09 UTC, juliaputko commented on smartsim/settings/arguments/launch/alps.py
> +    def format_env_vars(self, env_vars: t.Mapping[str, str | None]) -> list[str] | None:
changed

2024-08-20 21:09 UTC, juliaputko commented on smartsim/settings/arguments/launch/local.py
> +    def format_env_vars(self, env_vars: t.Mapping[str, str | None]) -> list[str] | None:
changed

2024-08-20 21:10 UTC, juliaputko commented on smartsim/settings/arguments/launch/mpi.py
> +    def format_env_vars(self, env_vars: t.Mapping[str, str | None]) -> list[str] | None:
changed

2024-08-20 21:10 UTC, juliaputko commented on smartsim/settings/arguments/launch/pals.py
> +    def format_env_vars(self, env_vars: t.Mapping[str, str | None]) -> list[str] | None:
changed

2024-08-20 21:11 UTC, juliaputko commented on smartsim/settings/arguments/launch/slurm.py
> +    def format_env_vars(self, env_vars: t.Mapping[str, str | None]) -> list[str] | None:
changed

2024-08-20 21:13 UTC, juliaputko commented on smartsim/_core/arguments/shell.py
> +    def format_launch_args(self) -> list[str] | None: ...
changed

2024-08-20 21:13 UTC, juliaputko commented on smartsim/settings/launchSettings.py
> +from smartsim._core.arguments.shell import ShellLaunchArguments
removed

2024-08-22 23:03 UTC, merged