Documentation Update for 0.3.2
CrayLabs/SmartSim pull request #71
Opened 2021-07-30 02:04 UTC by Spartee

The readme has been updated with new examples and
usage patterns.

A new Online Analysis examples has been created with
a Lattice Boltzman simulation that will show users
how to perform streaming analysis with Smartsim.

2021-07-30 16:10 UTC, al-rigazzi requested changes
Just some typos here and there. Looks stellar.

2021-08-02 20:09 UTC, EricGustin reviewed
Some more typos to address.

2021-08-02 20:09 UTC, EricGustin commented on README.md
> +# training code ommited
omitted

2021-08-02 20:09 UTC, EricGustin commented on README.md
> +into onnx format for use with SmartSim.
for consistency, `onnx` -> `ONNX`

2021-08-02 20:09 UTC, EricGustin commented on README.md
> +into f groups ("clusters"). Sci-kit Learn has a built in implementation of K-means clustering
`built in` -> `built-in`

2021-08-02 20:09 UTC, EricGustin commented on README.md
> +The Random Forest example uses the Iris datset from Sci-kit Learn to train a
dataset

2021-08-03 16:50 UTC, EricGustin requested changes
Changed most typo comments to suggestions.

2021-08-03 16:50 UTC, EricGustin commented on CITATION.cff
> +  - family-names: Gustavo
```suggestion
  - family-names: Marques
```

2021-08-03 16:50 UTC, EricGustin commented on CITATION.cff
> +    given-names: Marques
```suggestion
    given-names: Gustavo
```

2021-08-03 16:50 UTC, EricGustin commented on CITATION.cff
> +title: "Using Machine Learning at Scale in HPCSimulations with SmartSim: An Application to Ocean Climate Modeling"
```suggestion
title: "Using Machine Learning at Scale in HPC Simulations with SmartSim: An Application to Ocean Climate Modeling"
```

2021-08-03 16:50 UTC, EricGustin commented on doc/tutorials/lattice_boltz_analysis.rst
> +database and the simulation locally, but in seperate processes. The example
```suggestion
database and the simulation locally, but in separate processes. The example
```

2021-08-03 16:50 UTC, EricGustin commented on doc/tutorials/lattice_boltz_analysis.rst
> +Also defined is an `Orchestrator` which is the refrence to the in-memory database
```suggestion
Also defined is an `Orchestrator` which is the reference to the in-memory database
```

2021-08-03 16:50 UTC, EricGustin commented on doc/tutorials/lattice_boltz_analysis.rst
> +    # start simulation without blocking so data can be analyized in real time
```suggestion
    # start simulation without blocking so data can be analyzed in real time
```

2021-08-03 16:50 UTC, EricGustin commented on doc/tutorials/lattice_boltz_analysis.rst
> +SmartRedis is used  to pull the Datasets created by
```suggestion
SmartRedis is used to pull the Datasets created by
```

2021-08-03 16:50 UTC, EricGustin commented on doc/tutorials/lattice_boltz_analysis.rst
> +resources such as GPU enabled nodes, or distributed accross nodes.
```suggestion
resources such as GPU enabled nodes, or distributed across nodes.
```

2021-08-03 16:50 UTC, EricGustin commented on doc/tutorials/lattice_boltz_analysis.rst
> +This version, where the driver and anaylsis code coexist in the same
```suggestion
This version, where the driver and analysis code coexist in the same
```

2021-08-03 16:50 UTC, EricGustin commented on tutorials/03_online_analysis/lattice/driver.py
> +# start simulation without blocking so data can be analyized in real time
```suggestion
# start simulation without blocking so data can be analyzed in real time
```

2021-08-03 16:50 UTC, EricGustin commented on README.md
> +paradigm allows for data to be seemlessly exchanged between applications at runtime.
```suggestion
paradigm allows for data to be seamlessly exchanged between applications at runtime.
```

2021-08-03 16:50 UTC, EricGustin commented on README.md
> +In addition to exchanging data between langauges, any of the SmartRedis clients can
```suggestion
In addition to exchanging data between languages, any of the SmartRedis clients can
```

2021-08-03 16:50 UTC, EricGustin commented on README.md
> +the Orchestrator dispite which langauge the data originated from.
```suggestion
the Orchestrator despite which language the data originated from.
```

2021-08-03 16:50 UTC, EricGustin commented on README.md
> +for a batch script. Users can launch groups of ``Model`` instances in a ``Ensemble``.
```suggestion
for a batch script. Users can launch groups of ``Model`` instances in an ``Ensemble``.
```

2021-08-03 16:50 UTC, EricGustin commented on README.md
> +The following launches 4 replicas of the the same ``hello_world`` model.
```suggestion
The following launches 4 replicas of the same ``hello_world`` model.
```

2021-08-03 16:50 UTC, EricGustin commented on README.md
> +configurations and optional form a distributed database cluster. The examples
```suggestion
configurations and optionally form a distributed database cluster. The examples
```

2021-08-03 16:50 UTC, EricGustin commented on README.md
> +# launch models, anaylsis, training, inference sessions, etc
```suggestion
# launch models, analysis, training, inference sessions, etc
```

2021-08-03 16:50 UTC, EricGustin commented on README.md
> +# launch models, anaylsis, training, inference sessions, etc
```suggestion
# launch models, analysis, training, inference sessions, etc
```

2021-08-03 16:50 UTC, EricGustin commented on README.md
> +# launch models, anaylsis, training, inference sessions, etc
```suggestion
# launch models, analysis, training, inference sessions, etc
```

2021-08-03 16:50 UTC, EricGustin commented on README.md
> +# launch models, anaylsis, training, inference sessions, etc
```suggestion
# launch models, analysis, training, inference sessions, etc
```

2021-08-03 16:50 UTC, EricGustin commented on README.md
> +a NumPy array. The C++/C client accepts nested and contingous arrays.
```suggestion
a NumPy array. The C++/C client accepts nested and contiguous arrays.
```

2021-08-03 16:50 UTC, EricGustin commented on README.md
> +any language can recieve a tensor from the database no matter what supported language
```suggestion
any language can receive a tensor from the database no matter what supported language
```

2021-08-03 16:50 UTC, EricGustin commented on README.md
> +to see examples of how the API is used accross different languages even without the
```suggestion
to see examples of how the API is used across different languages even without the
```

2021-08-03 16:50 UTC, EricGustin commented on README.md
> +For more imformation on the SmartRedis clients, see the
```suggestion
For more information on the SmartRedis clients, see the
```

2021-08-03 16:50 UTC, EricGustin commented on README.md
> +shows how to take a PyTorch model, sent it to the database, and execute it
```suggestion
shows how to take a PyTorch model, send it to the database, and execute it
```

2021-08-03 16:50 UTC, EricGustin commented on README.md
> +  ! Construct the keys used for the specifiying inputs and outputs
```suggestion
  ! Construct the keys used for the specifying inputs and outputs
```

2021-08-03 16:50 UTC, EricGustin commented on README.md
> +SmartSim, applcations using the SmartRedis clients are directly connected to
```suggestion
SmartSim, applications using the SmartRedis clients are directly connected to
```

2021-08-03 16:50 UTC, EricGustin commented on README.md
> +# initialization code ommitted
```suggestion
# initialization code omitted
```

2021-08-03 16:50 UTC, EricGustin commented on README.md
> +More details about online anaylsis with SmartSim and the full code examples can be found in the
```suggestion
More details about online analysis with SmartSim and the full code examples can be found in the
```

2021-08-03 16:50 UTC, EricGustin commented on README.md
> +The processing capabilties make it simple to form computational piplines of
```suggestion
The processing capabilities make it simple to form computational pipelines of
```

2021-08-03 17:00 UTC, EricGustin commented on README.md
> +SmartSim supports the following frameworks for quering Machine Learning models
```suggestion
SmartSim supports the following frameworks for querying Machine Learning models
```

2021-08-03 17:02 UTC, EricGustin commented on doc/tutorials/inference.rst
> +The Random Forest example uses the Iris datset from Scikit Learn to train a
```suggestion
The Random Forest example uses the Iris dataset from Scikit Learn to train a
```

2021-08-06 04:55 UTC, merged